"""add_insights_and_pain_points

Revision ID: 6c963d2b735b
Revises: 4df3e2474ceb
Create Date: 2026-07-07 15:23:17.222433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c963d2b735b'
down_revision: Union[str, None] = '4df3e2474ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('feature_requests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('customer_sentiment', sa.Enum('positive', 'neutral', 'negative', 'mixed', name='insight_customer_sentiment'), nullable=False),
    sa.Column('customer_type', sa.String(length=100), nullable=False),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notable_quotes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id')
    )
    op.create_table('pain_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('pricing', 'reporting', 'authentication', 'onboarding', 'integrations', 'performance', 'ux', 'documentation', 'analytics', 'security', 'collaboration', 'support', name='pain_point_category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pain_points')
    op.drop_table('insights')
    # ### end Alembic commands ###
    # Postgres ENUM types aren't owned by a table and survive drop_table,
    # so they must be dropped explicitly or upgrade() fails on re-run with
    # "type already exists".
    sa.Enum(name='pain_point_category').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='insight_customer_sentiment').drop(op.get_bind(), checkfirst=True)
