"""add_interview_and_transcript_models

Revision ID: f3315afe77e6
Revises: 
Create Date: 2026-07-04 10:17:59.973851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3315afe77e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('pending', 'transcribing', 'processing', 'completed', 'failed', name='interview_status'), nullable=False),
    sa.Column('input_type', sa.Enum('audio', 'notes', name='interview_input_type'), nullable=False),
    sa.Column('raw_notes_text', sa.Text(), nullable=True),
    sa.Column('audio_s3_key', sa.String(length=1024), nullable=True),
    sa.Column('audio_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcripts')
    op.drop_table('interviews')
    # ### end Alembic commands ###
    # Postgres ENUM types are not owned by a table and survive drop_table,
    # so they must be dropped explicitly or upgrade() fails on re-run with
    # "type already exists".
    sa.Enum(name='interview_input_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='interview_status').drop(op.get_bind(), checkfirst=True)
